diff --git a/node_modules/@aragon/contract-helpers-test/src/asserts/assertThrow.js b/node_modules/@aragon/contract-helpers-test/src/asserts/assertThrow.js
index 8f6790e..7a8e7ca 100644
--- a/node_modules/@aragon/contract-helpers-test/src/asserts/assertThrow.js
+++ b/node_modules/@aragon/contract-helpers-test/src/asserts/assertThrow.js
@@ -4,6 +4,7 @@
 
 const ERROR_PREFIX = 'Returned error:'
 const THROW_PREFIX = 'VM Exception while processing transaction: revert'
+const THROW_PREFIX_V2 = 'VM Exception while processing transaction: reverted with reason string'
 
 async function assertThrows(
   blockOrPromise,
@@ -87,8 +88,10 @@
   if (!error.reason && error.message.includes(THROW_PREFIX)) {
     error.reason = error.message
       .replace(ERROR_PREFIX, '')
+      .replace(THROW_PREFIX_V2, '')
       .replace(THROW_PREFIX, '')
       .trim()
+      .replace(/^'|'$/g,"")
   }
 
   // Truffle v5 sometimes adds an extra ' -- Reason given: reason.' to the error message ðŸ¤·
